env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - prettier
overrides:
  - env:
      node: true
    files:
      - jest.config.ts
    parserOptions:
      sourceType: script
parserOptions:
  ecmaVersion: latest
  project:
    - tsconfig.json
  sourceType: module
plugins:
  - simple-import-sort
rules:
  simple-import-sort/imports: error
  simple-import-sort/exports: error
