name: Document
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/document.yml
      - src/**
      - README.md
permissions:
  contents: write
jobs:
  document:
    name: Deploy document to Github Wiki
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 22
      - name: Install dependencies
        run: pnpm i
      - name: Generate wiki
        run: pnpm run doc
      - name: Publish
        uses: Andrew-Chen-Wang/github-wiki-action@v4
